apiVersion: v1
kind: Pod
metadata:
  name: failed-multi-container-pod
spec:
  restartPolicy: Never
  containers:
    - name: nginx-container
      image: nginx:latest
    - name: debian-container
      image: debian:1212
      command: ["/bin/sh"]
      args: ["-c", "while true; do date;echo debian-container; sleep 5; done"]
