openapi: 3.0.4
info:
  title: Express server API
  description: Basic express server example
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
    description: Basic description,
paths:
  /welcome:
    get:
      summary: Returns a simple welcome message
      responses:
        "200":
          description: A simple message
          content:
            text/plain:
              schema:
                type: string
